
labelRegion={
"SignalRegion"  : "Signal Region",
"SideBand"      : "SideBand",
"ZRegion"       : "Z Region",
"ZRegion"       : "Z Region",
"TwoJetsTwoMu"  : "2 Jets and 2 opposite Muons",
}




labelVariable={
"LeadMuon_pt"       : "p_{T}(#mulead)",
"LeadMuon_eta"      : "#eta(#mu lead)",
"SubMuon_pt"        : "p_{T}(#mu sublead)",
"SubMuon_eta"       : "#eta(#mu sublead)",
"QJet0_eta"         : "#eta(leading jet)",
"QJet1_eta"         : "#eta(subleading jet)",
"QJet0_pt_nom"      : "p_{T}(#mu lead)",
"QJet1_pt_nom"      : "p_{T}(#mu sublead)",
"PV_npvs"           : "number of primary vertices",
"fixedGridRhoFastjetAll"           : "energy density #rho",
"LeadingSAJet_pt"   : "p_{T}(soft leading jet)",
"NSoft10New2"       : "# soft jet p_{T}>10",
"NSoft5New2"        : "# soft jet p_{T}>5",
"NSoft2New2"        : "# soft jet p_{T}>2",
"SAHT"              : "soft Activity HT",
"SAHT5"             : "soft Activity HT p_{T}>5",
"nFootprintSAJet"   : "nFootprintSAJet",
"FootHT"            : "FootHT",
"Mqq_log"           : "log( M(jj) )",
"Mqq_over400_log"   : "log( M(jj)/400 )",
"mmjj_pt"           : "p_{T}(#mu#mujj)",
"qqDeltaEta"        : "#Delta#eta(j,j)",
"NSoft5"            : "# soft jet p_{T}>5 old version",
"ll_zstar"          : "z*",
"Higgs_pt"          : "p_{T}(#mu#mu)",
"theta2"            : "cos(#mu#mu, subleading jet)",
"mmjj_pz"           : "p_{Z}(#mu#mujj)",
"MaxJetAbsEta"      : "max( |#eta(j lead)|, |#eta(j lead)| )",
"Higgs_m"           : "M(#mu#mu)",
"SBClassifier"      : "BDT output",
"BDTAtan"           : "BDTAtanh((BDT+1)/2)",
"Higgs_m_uncalib"   : "M(#mu#mu) uncalib",
"NSoft5New"         : "# soft jet p_{T}>5 equivalent version",
"ll_zstar_log"      : "log(z*)",
"SBClassifierZ"     : "BDT output (m=125)",
"BDTAtanZ"          : "atanh((BDT+1)/2) (m=125)",
"SBClassifierNoMass": "BDT output (m=125)",
"BDTAtanNoMass"     : "atanh((BDT+1)/2) (m=125)",
"DNN18Atan"         : "atanh(DNN)",
"DNN18AtanNoMass"   : "atanh(DNN) (m=125)",
"DNNAtan"           : "atanh(DNN)",
"DNNAtanNoMass"     : "atanh(DNN) (m=125)",
"DNNZAtan"          : "atanh(DNN Z vs DY)",
"DNNwithZAtan"           : "atanh(DNN with Z peak)",
"DNNwithZAtanNoMass"     : "atanh(DNN with Z peak) (m=125)",

}
